# Generated by Django 4.1.7 on 2023-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
